
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { io } from "socket.io-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    absolute: "",
    default: "",
    template: ""
  },
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        {/* Layout UI */}
        <main>{children}</main>
      </body>
    </html>
  )
}